server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
      - id: PasswordGenerator  #route identification
        uri: http://localhost:8091/
        predicates:
        - Path=/generate/**
        
       
      - id: PasswordStrengthChecker  #route identification
        uri: http://localhost:8092/
        predicates:
         - Path=/checkstrength/**